version: '2.3'
services:
  syslog:
    build:
      context: .
      dockerfile: ./docker/mozdef_syslog/Dockerfile
    restart: always
    command: /usr/sbin/syslog-ng --no-caps -F
    ports:
      - 514:514/udp
      - 514:514
    networks:
      - default
  honeycomb:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:1234
    networks:
      - default
    links:
      - syslog
    depends_on:
      - syslog
    volumes:
      - ./:/usr/share/honeycomb
    restart: unless-stopped
