version: '2.3'
services:
  honeycomb:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: INSERT_HOSTNAME
    domainname: INSERT_DOMAIN
    ports:
      - 80:1234
    environment:
      - HTTP_PROXY=INSERT_PROXY
      - HTTPS_PROXY=INSERT_PROXY
      - http_proxy=INSERT_PROXY
      - https_proxy=INSERT_PROXY
    networks:
      - default
    volumes:
      - ./:/usr/share/honeycomb
    restart: unless-stopped
